// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: CommonMessages_External.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message type
type ProtoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadType   *uint32                `protobuf:"varint,1,req,name=payloadType" json:"payloadType,omitempty"` // Type of payload
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`          // Payload
	ClientMsgId   *string                `protobuf:"bytes,3,opt,name=clientMsgId" json:"clientMsgId,omitempty"`  // Client message id, use this for matching the response with the initial request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	mi := &file_CommonMessages_External_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMessages_External_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessage.ProtoReflect.Descriptor instead.
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return file_CommonMessages_External_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMessage) GetPayloadType() uint32 {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return 0
}

func (x *ProtoMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProtoMessage) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

// Error response message
type ProtoErrorRes struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PayloadType             *ProtoPayloadType      `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=50" json:"payloadType,omitempty"` // Type of payload
	ErrorCode               *string                `protobuf:"bytes,2,req,name=errorCode" json:"errorCode,omitempty"`                                   // Error code
	Description             *string                `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`                               // Error description
	MaintenanceEndTimestamp *uint64                `protobuf:"varint,4,opt,name=maintenanceEndTimestamp" json:"maintenanceEndTimestamp,omitempty"`      // UNIX timestamp in milliseconds. If server is under maintenance, this field indicates the estimated time when the server will be operational again
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

// Default values for ProtoErrorRes fields.
const (
	Default_ProtoErrorRes_PayloadType = ProtoPayloadType_ERROR_RES
)

func (x *ProtoErrorRes) Reset() {
	*x = ProtoErrorRes{}
	mi := &file_CommonMessages_External_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoErrorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoErrorRes) ProtoMessage() {}

func (x *ProtoErrorRes) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMessages_External_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoErrorRes.ProtoReflect.Descriptor instead.
func (*ProtoErrorRes) Descriptor() ([]byte, []int) {
	return file_CommonMessages_External_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoErrorRes) GetPayloadType() ProtoPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoErrorRes_PayloadType
}

func (x *ProtoErrorRes) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *ProtoErrorRes) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProtoErrorRes) GetMaintenanceEndTimestamp() uint64 {
	if x != nil && x.MaintenanceEndTimestamp != nil {
		return *x.MaintenanceEndTimestamp
	}
	return 0
}

// Heartbeat used for keeping connection alive
type ProtoHeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadType   *ProtoPayloadType      `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=51" json:"payloadType,omitempty"` // Type of payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ProtoHeartbeatEvent fields.
const (
	Default_ProtoHeartbeatEvent_PayloadType = ProtoPayloadType_HEARTBEAT_EVENT
)

func (x *ProtoHeartbeatEvent) Reset() {
	*x = ProtoHeartbeatEvent{}
	mi := &file_CommonMessages_External_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoHeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoHeartbeatEvent) ProtoMessage() {}

func (x *ProtoHeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMessages_External_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoHeartbeatEvent.ProtoReflect.Descriptor instead.
func (*ProtoHeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_CommonMessages_External_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoHeartbeatEvent) GetPayloadType() ProtoPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoHeartbeatEvent_PayloadType
}

// Message used for sending a ping request to the server
type ProtoPingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadType   *ProtoPayloadType      `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=52" json:"payloadType,omitempty"`
	Timestamp     *uint64                `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"` // UNIX timestamp in milliseconds, you will receive a response with the same timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ProtoPingReq fields.
const (
	Default_ProtoPingReq_PayloadType = ProtoPayloadType_PING_REQ
)

func (x *ProtoPingReq) Reset() {
	*x = ProtoPingReq{}
	mi := &file_CommonMessages_External_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPingReq) ProtoMessage() {}

func (x *ProtoPingReq) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMessages_External_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPingReq.ProtoReflect.Descriptor instead.
func (*ProtoPingReq) Descriptor() ([]byte, []int) {
	return file_CommonMessages_External_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoPingReq) GetPayloadType() ProtoPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoPingReq_PayloadType
}

func (x *ProtoPingReq) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

// Response to a ProtoPingReq message
type ProtoPingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadType   *ProtoPayloadType      `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=53" json:"payloadType,omitempty"`
	Timestamp     *uint64                `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"` // UNIX timestamp in milliseconds, this is the timestamp of the request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ProtoPingRes fields.
const (
	Default_ProtoPingRes_PayloadType = ProtoPayloadType_PING_RES
)

func (x *ProtoPingRes) Reset() {
	*x = ProtoPingRes{}
	mi := &file_CommonMessages_External_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPingRes) ProtoMessage() {}

func (x *ProtoPingRes) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMessages_External_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPingRes.ProtoReflect.Descriptor instead.
func (*ProtoPingRes) Descriptor() ([]byte, []int) {
	return file_CommonMessages_External_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoPingRes) GetPayloadType() ProtoPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoPingRes_PayloadType
}

func (x *ProtoPingRes) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_CommonMessages_External_proto protoreflect.FileDescriptor

var file_CommonMessages_External_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x5f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x22, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x5f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49,
	0x64, 0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x09, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x17, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x17, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5b, 0x0a,
	0x13, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x0f, 0x48, 0x45,
	0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x52, 0x0b, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6b, 0x0a, 0x0c, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x0b, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x3a, 0x08, 0x50, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x52, 0x0b, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x6b, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x3a,
	0x08, 0x50, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6c, 0x2f, 0x63, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x61, 0x70, 0x69,
	0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
})

var (
	file_CommonMessages_External_proto_rawDescOnce sync.Once
	file_CommonMessages_External_proto_rawDescData []byte
)

func file_CommonMessages_External_proto_rawDescGZIP() []byte {
	file_CommonMessages_External_proto_rawDescOnce.Do(func() {
		file_CommonMessages_External_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CommonMessages_External_proto_rawDesc), len(file_CommonMessages_External_proto_rawDesc)))
	})
	return file_CommonMessages_External_proto_rawDescData
}

var file_CommonMessages_External_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_CommonMessages_External_proto_goTypes = []any{
	(*ProtoMessage)(nil),        // 0: ProtoMessage
	(*ProtoErrorRes)(nil),       // 1: ProtoErrorRes
	(*ProtoHeartbeatEvent)(nil), // 2: ProtoHeartbeatEvent
	(*ProtoPingReq)(nil),        // 3: ProtoPingReq
	(*ProtoPingRes)(nil),        // 4: ProtoPingRes
	(ProtoPayloadType)(0),       // 5: ProtoPayloadType
}
var file_CommonMessages_External_proto_depIdxs = []int32{
	5, // 0: ProtoErrorRes.payloadType:type_name -> ProtoPayloadType
	5, // 1: ProtoHeartbeatEvent.payloadType:type_name -> ProtoPayloadType
	5, // 2: ProtoPingReq.payloadType:type_name -> ProtoPayloadType
	5, // 3: ProtoPingRes.payloadType:type_name -> ProtoPayloadType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_CommonMessages_External_proto_init() }
func file_CommonMessages_External_proto_init() {
	if File_CommonMessages_External_proto != nil {
		return
	}
	file_CommonModelMessages_External_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CommonMessages_External_proto_rawDesc), len(file_CommonMessages_External_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonMessages_External_proto_goTypes,
		DependencyIndexes: file_CommonMessages_External_proto_depIdxs,
		MessageInfos:      file_CommonMessages_External_proto_msgTypes,
	}.Build()
	File_CommonMessages_External_proto = out.File
	file_CommonMessages_External_proto_goTypes = nil
	file_CommonMessages_External_proto_depIdxs = nil
}
